# Resume AI Configuration

# Ollama Model Settings
ollama:
  model: llama2
  temperature: 0.7
  max_tokens: 1024

# Resume Generation Preferences
resume:
  default_type: PROFESSIONAL
  export_formats:
    - pdf
    - docx

# Logging Configuration
logging:
  level: INFO
  file: resume_ai.log

# Optional: ATS Optimization Settings
ats_optimization:
  enabled: true
  keywords_file: industry_keywords.json